# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/Recipe

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
         command: |
                  sudo chmod +x gradlew
                  ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run:
          command: |
            sudo chmod +x gradlew
            ./gradlew test

      - run:
          name: "Build and Publish Release on GitHub"
          command: |
            NOW="$(date)" 
            ZIP_FILE_NAME=ExampleApp
            TAG=Release-$(date '+%Y-%m-%d-%H-%M-%S')
            ./gradlew jar
            cd ./build/libs/
            zip ${ZIP_FILE_NAME}.zip Recipe.jar 
            github-release upload --token ${GITHUB_TOKEN} --owner ${PROJECT_USERNAME} --repo ${PROJECT_REPONAME} --tag ${TAG} --name ${TAG} --body "Release date: ${NOW}" ${ZIP_FILE_NAME}.zip
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main